#!/bin/bash

echo "> (utilizado para direcionar um diretorio ou arquivo e se o tal arquivo estiver presente, será sobrescrito)"
echo -e "ls \$1 > ~/Documentos/Rafael\n"
echo ">> (utilizado para direcionar u diretório ou arquivo e se tal arquivo estiver presente, o comando terá saída no final do arquivo)"
echo -e "ls \$1 >> ~/Documentos/Rafael\n"
echo "2> (utilizado para redirecionar os erros gerados para um arquivo específico e mesmo não havendo erros, é criado tal arquivo)"
echo -e "ls \$1 2> /dev/null ou ls \$1 2> ~/Documentos/Rafael\n"
echo "2>> (utilizado para redirecionar os erros gerados para o final de um arquivo sem sobrescrever casa já tenha algo no arquivo)"
echo -e "ls \$1 2>> erro.log\n"
echo "&> (utilizado para redirecionar todas as saídas para um arquivo, e se houver algo dentro do arquivo será sobrescrito, e o arquivo será criado caso não exista)"
echo -e "ls \$1 &> ~/Documentos/Rafael\n"
echo "&>> (utilizaso para redirecionar todas as saídas para o final de um arquivo sem sobrescrever)"
echo -e "ls -l scripts &>> Lista2.txt\n"
echo "< (utilizado para informar ao shell que a entrada padrão será um arquivo específico)"
echo -e "grep rafael < lista2.txt\n"
echo "<< (utilizado para permitir redirecionar um arquivo a entrada padrão)"
echo -e "grep shellscript << fim\n"
echo "<<< (herestring utilizado para redirecionar um bloco de strings para um comando"
echo -e "cat <<< 'mengão é o melhor time do mundo'\n"
echo "| (utilizado para enviar a saída de um comando para a entrada de outro comando)"
echo -e "cat mengão.txt | wc -l\n"
